allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.matching { it.name.contains("AarMetadata") }.configureEach {
        enabled = false
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.plugins.withId("com.android.library") {
        project.android {
            compileSdkVersion 36
        }
    }
    project.plugins.withId("com.android.application") {
        project.android {
            compileSdkVersion 36
        }
    }
    tasks.matching { it.name.contains("AarMetadata") }.configureEach {
        enabled = false
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
